version: '3'

services:
  jenkins:
    build:
      context: jenkins/
    privileged: true
    restart: always
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
      - $HOME/.ssh/:/root/.ssh/
      - $HOME/.ssh/id_rsa:/var/jenkins_home/.ssh/id_rsa
      - $HOME/.ssh/id_rsa.pub:/var/jenkins_home/.ssh/id_rsa.pub
    depends_on:
      - sonarqube
    links:
        - sonarqube:sonarqube
  sonarqube:
    build:
      context: sonarqube/
    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube
